module.exports = function (content) {

    var entities = [
        ['Á', '&Aacute;'],
        ['Â', '&Acirc;'],
        ['Ã', '&Atilde;'],
        ['Ä', '&Auml;'],
        ['Å', '&Aring;'],
        ['Æ', '&AElig;'],
        ['Ç', '&Ccedil;'],
        ['È', '&Egrave;'],
        ['É', '&Eacute;'],
        ['Ê', '&Ecirc;'],
        ['Ë', '&Euml;'],
        ['Ì', '&Igrave;'],
        ['Í', '&Iacute;'],
        ['Î', '&Icirc;'],
        ['Ï', '&Iuml;'],
        ['Ð', '&ETH;'],
        ['Ñ', '&Ntilde;'],
        ['Ò', '&Ograve;'],
        ['Ó', '&Oacute;'],
        ['Ô', '&Ocirc;'],
        ['Õ', '&Otilde;'],
        ['Ö', '&Ouml;'],
        ['Ø', '&Oslash;'],
        ['Ù', '&Ugrave;'],
        ['Ú', '&Uacute;'],
        ['Û', '&Ucirc;'],
        ['Ü', '&Uuml;'],
        ['Ý', '&Yacute;'],
        ['Þ', '&THORN;'],
        ['ß', '&szlig;'],
        ['à', '&agrave;'],
        ['á', '&aacute;'],
        ['â', '&acirc;'],
        ['ã', '&atilde;'],
        ['ä', '&auml;'],
        ['å', '&aring;'],
        ['æ', '&aelig;'],
        ['ç', '&ccedil;'],
        ['è', '&egrave;'],
        ['é', '&eacute;'],
        ['ê', '&ecirc;'],
        ['ë', '&euml;'],
        ['ì', '&igrave;'],
        ['í', '&iacute;'],
        ['î', '&icirc;'],
        ['ï', '&iuml;'],
        ['ð', '&eth;'],
        ['ñ', '&ntilde;'],
        ['ò', '&ograve;'],
        ['ó', '&oacute;'],
        ['ô', '&ocirc;'],
        ['õ', '&otilde;'],
        ['ö', '&ouml;'],
        ['ø', '&oslash;'],
        ['ù', '&ugrave;'],
        ['ú', '&uacute;'],
        ['û', '&ucirc;'],
        ['ü', '&uuml;'],
        ['ý', '&yacute;'],
        ['þ', '&thorn;'],
        ['ÿ', '&yuml;'],
        ['®', '&reg;'],
        ['™', '&trade;'],
        ['°', '&deg;'],
        ['œ', '&oelig;'],
        ['µ', '&micro;'],
        ['’', '&rsquo;'],
        ['‚', '&sbquo;'],
        ['“', '&ldquo;'],
        ['„', '&bdquo;'],
        ['•', '&bull;'],
        ['”', '&rdquo;'],
        ["€", "&euro;"]
    ];

    entities.forEach(function (tab, i) {
        content = content.replace(new RegExp(tab[0], "g"), tab[1]);
    });

    return content;
};
